### ISSUE TITLE
SimpleJSON license

### ISSUE THREAD

**Issue by uerceg** [opless/SimpleJSON#1]
Hello there.

As far as I see, your SimpleJSON fork is pretty much todays official version which is widely used within Unity3d community. Also, as far as I saw, official version of SimpleJSON is the one from @bunny83: https://github.com/bunny83/SimpleJSON

In there, he added MIT license to it. On the other side, your version doesn't have any and also in source code comments on the top of file there's no license text.

Did you ever consider adding license text to SimpleJSON.cs comments so that users can be sure under which license it is published?

Cheers

**Comment by opless** [comment]
As I mentioned in the ReadMe, it's from the Unity wiki.

I shall attempt to contact Bunny83, to see if we can get my changes folded into theirs.

**Comment by uerceg** [comment]
Great, looking forward to. :+1:

**Comment by opless** [comment]
Also edited the readme to point at the original authors repo and a brief comment on the license.

**Comment by uerceg** [comment]
Awesome, thanks for the update.

**Comment by HenrikPoulsen** [comment]
I also have my own fork of this same thing (https://github.com/HenrikPoulsen/SimpleJSON ), though with additional changes (unit tests, bug fixes, performance improvements etc). Would be nice if we could have one repository for it and link to it in the unify wiki to make it easier for the community to contribute to this.

**Comment by opless** [comment]
+1.

**Comment by uerceg** [comment]
Any update on this issue maybe?

**Comment by Bunny83** [comment]
I'm sorry this request has passed me silently ^^.

I barely use git / github. The only reason why i actually created the repository was a request from a user who wanted to use it in an commercial project. He was unsure about the license. Things posted on Wikipedia (and most wiki-like sites) are actually not public domain but released under "creative commons". Creative commons is a bit nasty since it requires you to include attribution even when you build something on top of the licensed work. The Unity wiki seems to reference: https://creativecommons.org/licenses/by-sa/3.0/

That's why i actually added an MIT license since it's less problematic. I doubt that any author on the Unity wiki will require attribution but legally it could be a problem.

I don't really update the github repo. ^^ Recently i edited the wiki version and replaced the two temp string variables (Token and TokenName) with StringBuilders since someone had massive problems when parsing json which contains large data fields like a serialized image (resulted in massive garbage strings and long loading times).

I originally wrote the parser because i had a sudden need of a simple solution. That's why JSONData isn't well suited for building json. To actually clean up the whole thing one would create seperate classes for each actual "type". I also regret the chosen name "JSONClass" which should have been JSONObject but i wanted to keep it backward compatible ^^.

So, i currently don't have much time and don't really know how we should solve that ^^. Personally i don't really care about attribution. I'm happy if it helps you. I think the MIT license is usually the best choice. If it simply sticks inside the code file as comment nobody is really hurt and builds don't require attribution. Though i'm not sure if one can actually add an MIT license to the wiki post. My recherche seems to show that the MIT license isn't really compatible with creative commons. So keeping a git repo might be the best solution.

Again, sorry for the long delay (and the long comment) ^^. I barely read emails since it's usually just spammed with UnityAnswers notifications :)

**Comment by opless** [comment]
Thanks @Bunny83 👍
